server:
  port: 9013
spring:
  application:
    name: system-mnt
  freemarker:
    check-template-location: false
  profiles:
    active: dev
  data:
    redis:
      repositories:
        enabled: false
  #  pid:
  #    file: /自行指定位置/eladmin.pid
  redis:
    #数据库索引
    database: ${REDIS_DB:0}
    host: ${REDIS_HOST:127.0.0.1}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PWD:}
    #连接超时时间
    timeout: 5000