server:
  port: 9013
spring:
  application:
    name: system-mnt
  freemarker:
    check-template-location: false
  profiles:
    active: dev
  data:
    redis:
      repositories:
        enabled: false
  #  pid:
  #    file: /自行指定位置/eladmin.pid
  redis:
    #数据库索引
    database: ${REDIS_DB:0}
    host: ${REDIS_HOST:127.0.0.1}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PWD:}
    #连接超时时间
    timeout: 5000

# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    enabled: false # 不使用swagger-ui.html
  api-docs:
    path: /v3/api-docs
    enabled: true
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: cn.lyn4ever.mnt.rest
# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn